table Customers
	lineageTag: 0adfb9ea-bcea-4f39-8275-f8bd865ebbe5

	measure 'Member Cards' = COUNT(Customers[member_card])
		formatString: 0
		lineageTag: 8545e2fb-3f62-4df2-9b73-b0216d67e977

	measure 'Average Estimated Income' = ```
			AVERAGE(Customers[Estimated Income])
			
			```
		lineageTag: 17332c9e-75b1-47ed-9d8d-bd596d8fd818

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: c0558311-4fe9-4e79-9c84-a95fe9790500
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: int64
		formatString: 0
		lineageTag: 6c1c930b-6dd0-48f8-927a-f146730fa1b7
		summarizeBy: sum
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 302472e6-c264-43e2-a22c-bd1067b2c7c7
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 392fb6e1-1702-45fc-89cb-e6a4a4524d9b
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column customer_address
		dataType: string
		lineageTag: 6984d24b-3b72-4dcd-8f4f-2bd77d8b1892
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 949dc42f-f19f-418e-993a-e6a48f27ddd5
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state_province
		dataType: string
		lineageTag: bc77f01f-254f-46d6-b0cb-94db819098bf
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: int64
		formatString: 0
		lineageTag: 0b67af2c-7df5-4c5f-962b-eca2f1c08a9d
		summarizeBy: sum
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: 429ca925-8997-4117-bc69-59784174a032
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column birthdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5142f884-dfa9-4caf-a504-a016ad89cf3f
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: becfcb9c-31ba-4eff-9004-83a05291124a
			defaultHierarchy: LocalDateTable_1ed94b06-2553-4b6c-9940-f3d748026af7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 3b68ccee-8fd6-496e-ae1f-1f6f017632a7
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column yearly_income
		dataType: string
		lineageTag: f98bd66f-4408-4082-8c62-b1e2db7ed6ad
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 5d00ad1c-15ae-4ff3-bbca-5efeea96e9c5
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: 94e01f7f-2902-4c08-a9a9-8cd5cbf86826
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 82a62470-ad24-46cb-bb9c-d564abc7b0c4
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: f8f22801-01c9-469b-bb94-bdd60f426c4b
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column acct_open_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d83d4eab-565d-4da4-a376-f98aeaef5ded
		summarizeBy: none
		sourceColumn: acct_open_date

		variation Variation
			isDefault
			relationship: 321a9088-1452-494a-9604-381837f1741a
			defaultHierarchy: LocalDateTable_040a6f17-8921-4056-ade1-68b8cd47e758.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 1ede0abb-883d-4ecd-98d6-3c19c834d5dd
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

	column occupation
		dataType: string
		lineageTag: 619cf635-3001-4e8a-a0b3-334c8c54fb4e
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

	column homeowner
		dataType: string
		lineageTag: f7985f3a-920f-4384-9831-9b0db9ff4d4f
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

	column Age = DATEDIFF(Customers[birthdate], DATE(1997,1,1), YEAR)
		formatString: 0
		lineageTag: 4f585695-714a-4366-a49b-d744eb9ca421
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Age Group' = ```
			
			SWITCH(
			    TRUE(),
			    Customers[Age] <= 25, "18-25",
			    Customers[Age] <= 40, "26-40",
			    Customers[Age] <= 60, "41-60",
			    "60+"
			)
			
			```
		lineageTag: 642b6aba-ebae-46fa-9ccb-4e0e69e3ac7d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Type' = ```
			
			IF(
			    Customers[homeowner] = "Y" && Customers[member_card] = "Golden",
			    "Elite",
			    "Regular"
			)
			
			```
		lineageTag: f2328ebe-dcba-403d-8b49-43d9c6fda7b0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Estimated Income' =
			
			SWITCH(
			    TRUE(),
			    SEARCH("Under 30k", Customers[yearly_income], 1, 0) > 0, 30000,
			    SEARCH("50k", Customers[yearly_income], 1, 0) > 0, 50000,
			    SEARCH("70k", Customers[yearly_income], 1, 0) > 0, 70000,
			    SEARCH("90k", Customers[yearly_income], 1, 0) > 0, 90000,
			    SEARCH("110k", Customers[yearly_income], 1, 0) > 0, 110000,
			    SEARCH("130k", Customers[yearly_income], 1, 0) > 0, 130000,
			    SEARCH("150k", Customers[yearly_income], 1, 0) > 0, 150000,
			SEARCH("+150k", Customers[yearly_income], 1, 0) < 0, 150000,
			BLANK())
		formatString: 0
		lineageTag: 29695f69-ea7c-4d35-9b68-bb57ce2aac7f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\hamo0\Downloads\project\project\Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", Int64.Type}, {"customer_country", type text}, {"birthdate", type date}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type date}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","m","1",Replacer.ReplaceText,{"gender"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","M","1",Replacer.ReplaceText,{"gender"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","F","0",Replacer.ReplaceText,{"gender"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value2",{{"gender", type text}}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Changed Type1","0","F",Replacer.ReplaceText,{"gender"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","1","M",Replacer.ReplaceText,{"gender"})
				in
				    #"Replaced Value4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

